# Generated by Django 4.0.5 on 2022-07-04 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FEEDBACKS', '0003_feedback_timestamp_feedback_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
