# Generated by Django 4.0.5 on 2022-07-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FEEDBACKS', '0004_feedback_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='type',
            new_name='comment_type',
        ),
    ]
